/**
 * Mock employee data for JPMC Payroll — Philippine context.
 *
 * Roles: 2 admin, 2 moderator, 6 employee
 * Each employee contains TWO payroll periods + separate audit logs.
 */

function splitPayroll(payroll) {
  const totalDays = payroll.work_days;
  const period1Days = Math.ceil(totalDays / 2);
  const period2Days = totalDays - period1Days;

  const splitValue = (val) => {
    if (val === 0) return [0, 0];
    const half = val / 2;
    return [Math.round(half * 100) / 100, Math.round(half * 100) / 100];
  };

  const [
    holiday_pay_1, holiday_pay_2
  ] = splitValue(payroll.holiday_pay);
  const [snwh_pay_1, snwh_pay_2] = splitValue(payroll.snwh_pay);
  const [wellness_1, wellness_2] = splitValue(payroll.wellness_allowance);
  const [comm_1, comm_2] = splitValue(payroll.communication_allowance);
  const [bday_1, bday_2] = splitValue(payroll.birthday_allowance);
  const [commission_1, commission_2] = splitValue(payroll.commission);
  const [allowance_1, allowance_2] = splitValue(payroll.allowance);
  const [bonuses_1, bonuses_2] = splitValue(payroll.bonuses);
  const [thirteenth_1, thirteenth_2] = splitValue(payroll.thirteenth_month_pay);
  const [cash_adv_1, cash_adv_2] = splitValue(payroll.cash_advance);
  const [sss_1, sss_2] = splitValue(payroll.sss);
  const [philhealth_1, philhealth_2] = splitValue(payroll.philhealth);
  const [pagibig_1, pagibig_2] = splitValue(payroll.pagibig);
  const [hmo_1, hmo_2] = splitValue(payroll.hmo);
  const [others_1, others_2] = splitValue(payroll.others);

  return {
    period1: {
      daily_pay: payroll.daily_pay,
      work_days: period1Days,
      holiday_pay: holiday_pay_1,
      snwh_pay: snwh_pay_1,
      wellness_allowance: wellness_1,
      communication_allowance: comm_1,
      birthday_allowance: bday_1,
      commission: commission_1,
      allowance: allowance_1,
      bonuses: bonuses_1,
      thirteenth_month_pay: thirteenth_1,
      cash_advance: cash_adv_1,
      sss: sss_1,
      philhealth: philhealth_1,
      pagibig: pagibig_1,
      hmo: hmo_1,
      others: others_1,
    },
    period2: {
      daily_pay: payroll.daily_pay,
      work_days: period2Days,
      holiday_pay: holiday_pay_2,
      snwh_pay: snwh_pay_2,
      wellness_allowance: wellness_2,
      communication_allowance: comm_2,
      birthday_allowance: bday_2,
      commission: commission_2,
      allowance: allowance_2,
      bonuses: bonuses_2,
      thirteenth_month_pay: thirteenth_2,
      cash_advance: cash_adv_2,
      sss: sss_2,
      philhealth: philhealth_2,
      pagibig: pagibig_2,
      hmo: hmo_2,
      others: others_2,
    },
  };
}

const baseEmployees = [
  {
    id: "EMP001",
    name: "Juan Dela Cruz",
    position: "HR Director",
    department: "Human Resources",
    role: "admin",
    email: "juan.delacruz@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 1363.64,
      work_days: 22,
      holiday_pay: 3000,
      snwh_pay: 1000,
      wellness_allowance: 1500,
      communication_allowance: 1000,
      birthday_allowance: 0,
      commission: 0,
      allowance: 2000,
      bonuses: 5000,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 1350,
      philhealth: 675,
      pagibig: 200,
      hmo: 1500,
      others: 0,
    },
  },
  {
    id: "EMP002",
    name: "Maria Santos",
    position: "Finance Manager",
    department: "Finance",
    role: "admin",
    email: "maria.santos@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 1590.91,
      work_days: 22,
      holiday_pay: 3500,
      snwh_pay: 1200,
      wellness_allowance: 1500,
      communication_allowance: 1200,
      birthday_allowance: 500,
      commission: 0,
      allowance: 2500,
      bonuses: 8000,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 1350,
      philhealth: 675,
      pagibig: 200,
      hmo: 1800,
      others: 0,
    },
  },
  {
    id: "EMP003",
    name: "Pedro Reyes",
    position: "Engineering Lead",
    department: "Engineering",
    role: "moderator",
    email: "pedro.reyes@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 1454.55,
      work_days: 22,
      holiday_pay: 3200,
      snwh_pay: 1100,
      wellness_allowance: 1500,
      communication_allowance: 1000,
      birthday_allowance: 0,
      commission: 0,
      allowance: 2200,
      bonuses: 6000,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 1350,
      philhealth: 675,
      pagibig: 200,
      hmo: 1600,
      others: 0,
    },
  },
  {
    id: "EMP004",
    name: "Ana Gonzales",
    position: "Operations Manager",
    department: "Operations",
    role: "moderator",
    email: "ana.gonzales@jpmc.com",
    status_period1: "Pending",
    status_period2: "Pending",
    payroll: {
      daily_pay: 1318.18,
      work_days: 20,
      holiday_pay: 2800,
      snwh_pay: 950,
      wellness_allowance: 1500,
      communication_allowance: 1000,
      birthday_allowance: 0,
      commission: 0,
      allowance: 2000,
      bonuses: 4500,
      thirteenth_month_pay: 0,
      cash_advance: 3000,
      sss: 1350,
      philhealth: 675,
      pagibig: 200,
      hmo: 1400,
      others: 500,
    },
  },
  {
    id: "EMP005",
    name: "Ricardo Lim",
    position: "Software Developer",
    department: "Engineering",
    role: "employee",
    email: "ricardo.lim@jpmc.com",
    status_period1: "Pending",
    status_period2: "Pending",
    payroll: {
      daily_pay: 772.73,
      work_days: 22,
      holiday_pay: 1700,
      snwh_pay: 600,
      wellness_allowance: 1000,
      communication_allowance: 800,
      birthday_allowance: 0,
      commission: 0,
      allowance: 1200,
      bonuses: 2500,
      thirteenth_month_pay: 0,
      cash_advance: 1500,
      sss: 900,
      philhealth: 450,
      pagibig: 200,
      hmo: 800,
      others: 200,
    },
  },
  {
    id: "EMP006",
    name: "Carmen Tan",
    position: "UI/UX Designer",
    department: "Engineering",
    role: "employee",
    email: "carmen.tan@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 681.82,
      work_days: 21,
      holiday_pay: 1500,
      snwh_pay: 500,
      wellness_allowance: 1000,
      communication_allowance: 800,
      birthday_allowance: 500,
      commission: 0,
      allowance: 1000,
      bonuses: 2000,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 810,
      philhealth: 405,
      pagibig: 200,
      hmo: 700,
      others: 0,
    },
  },
  {
    id: "EMP007",
    name: "Roberto Sy",
    position: "QA Engineer",
    department: "Engineering",
    role: "employee",
    email: "roberto.sy@jpmc.com",
    status_period1: "Pending",
    status_period2: "Pending",
    payroll: {
      daily_pay: 636.36,
      work_days: 22,
      holiday_pay: 1400,
      snwh_pay: 450,
      wellness_allowance: 1000,
      communication_allowance: 600,
      birthday_allowance: 0,
      commission: 0,
      allowance: 900,
      bonuses: 1800,
      thirteenth_month_pay: 0,
      cash_advance: 1000,
      sss: 720,
      philhealth: 360,
      pagibig: 200,
      hmo: 650,
      others: 150,
    },
  },
  {
    id: "EMP008",
    name: "Lourdes Cruz",
    position: "HR Specialist",
    department: "Human Resources",
    role: "employee",
    email: "lourdes.cruz@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 590.91,
      work_days: 21,
      holiday_pay: 1300,
      snwh_pay: 400,
      wellness_allowance: 1000,
      communication_allowance: 600,
      birthday_allowance: 0,
      commission: 0,
      allowance: 800,
      bonuses: 1500,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 675,
      philhealth: 338,
      pagibig: 200,
      hmo: 600,
      others: 0,
    },
  },
  {
    id: "EMP009",
    name: "Eduardo Reyes",
    position: "Accountant",
    department: "Finance",
    role: "employee",
    email: "eduardo.reyes@jpmc.com",
    status_period1: "Pending",
    status_period2: "Pending",
    payroll: {
      daily_pay: 613.64,
      work_days: 22,
      holiday_pay: 1350,
      snwh_pay: 420,
      wellness_allowance: 1000,
      communication_allowance: 600,
      birthday_allowance: 0,
      commission: 0,
      allowance: 850,
      bonuses: 1600,
      thirteenth_month_pay: 0,
      cash_advance: 2000,
      sss: 720,
      philhealth: 360,
      pagibig: 200,
      hmo: 650,
      others: 100,
    },
  },
  {
    id: "EMP010",
    name: "Josefina Bautista",
    position: "Marketing Specialist",
    department: "Marketing",
    role: "employee",
    email: "josefina.bautista@jpmc.com",
    status_period1: "Approved",
    status_period2: "Approved",
    payroll: {
      daily_pay: 568.18,
      work_days: 21,
      holiday_pay: 1250,
      snwh_pay: 380,
      wellness_allowance: 1000,
      communication_allowance: 600,
      birthday_allowance: 500,
      commission: 1500,
      allowance: 750,
      bonuses: 1400,
      thirteenth_month_pay: 0,
      cash_advance: 0,
      sss: 630,
      philhealth: 315,
      pagibig: 200,
      hmo: 550,
      others: 0,
    },
  },
];

export const mockEmployees = baseEmployees.map((emp) => {
  const { period1, period2 } = splitPayroll(emp.payroll);
  return {
    ...emp,
    payroll_period1: period1,
    payroll_period2: period2,
    auditLog_period1: [],
    auditLog_period2: [],
  };
});
